import React from 'react';
import { Shield, ArrowLeft } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useSEO } from '../hooks/useSEO';

const PrivacyPolicy = () => {
  useSEO({
    title: 'Privacy Policy | URLScanOnline',
    description: 'Learn how URLScanOnline handles account information, scan data, scan history, access controls, data retention, and privacy.',
    path: '/privacy-policy'
  });

  return (
    <div className="flex-1 w-full max-w-4xl mx-auto p-4 sm:p-6 lg:p-8 overflow-y-auto space-y-12 pb-24">

      {/* Back Link */}
      <div className="-mb-4">
        <Link
          to="/trust-policy"
          className="inline-flex items-center gap-2 text-sm text-slate-400 hover:text-indigo-400 transition-colors focus:outline-none focus:ring-2 focus:ring-indigo-500 rounded-md px-1 py-0.5 -ml-1"
        >
          <ArrowLeft className="w-4 h-4" />
          Back to Trust & Policy
        </Link>
      </div>

      <header className="space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 text-blue-400 text-sm font-semibold mb-2">
          <Shield className="w-4 h-4" />
          Privacy
        </div>
        <h1 className="text-4xl md:text-5xl font-black text-slate-50 tracking-tight">
          Privacy Policy
        </h1>
        <p className="text-lg text-slate-400 max-w-2xl">
          Learn how URLScanOnline collects, uses, stores, and protects information associated with your use of the service.
        </p>
        <div className="text-sm text-slate-500 pt-4">
          Last updated: September 2026
        </div>
      </header>

      <div className="space-y-8">

        {/* Section 1 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">1. Information We Collect</h2>
          <p className="text-slate-400 leading-relaxed mb-4">
            We only collect information necessary to operate URLScanOnline and provide its core security scanning functionality:
          </p>
          <ul className="space-y-3 text-slate-400">
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span><strong className="text-slate-300">Account Information:</strong> If you create an account, we collect basic account information such as your email address.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span><strong className="text-slate-300">Scan Target Information:</strong> The domain names or URLs you submit to the scanner for analysis.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span><strong className="text-slate-300">Scan Results:</strong> Security findings and report data generated by our automated checks.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span><strong className="text-slate-300">Technical/Service Information:</strong> Technical information, such as an IP address, may be processed where needed for rate limiting, security, and abuse prevention.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span><strong className="text-slate-300">Contact Information:</strong> Information you voluntarily submit when contacting our support or security teams.</span>
            </li>
          </ul>
        </section>

        {/* Section 2 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">2. Scan Data & Scan History</h2>
          <div className="space-y-4 text-slate-400 leading-relaxed">
            <p>
              URLScanOnline does not maintain scan history for general administrative browsing or make one user's scan records available to another user.
            </p>
            <p>
              For authenticated users, scan records may be stored to provide account features such as Scan History and Saved Reports. These records are associated with the user's account so that the user can return to previous results.
            </p>
            <p>
              Normal application access is owner-scoped. A signed-in user can access only scan records associated with their own account.
            </p>
            <p>
              URLScanOnline administrators do not have a general Admin Control interface for browsing individual users' scan histories. Aggregate, non-identifying statistics (such as total platform scan counts) may be used for platform administration without exposing individual scan records.
            </p>
          </div>
        </section>

        {/* Section 3 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">3. Guest Scans</h2>
          <p className="text-slate-400 leading-relaxed">
            Guest scans are processed to generate the requested report and are not persisted to an account scan-history database. Technical information such as an IP address may be processed for rate limiting and abuse prevention.
          </p>
        </section>

        {/* Section 4 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">4. How We Use Information</h2>
          <p className="text-slate-400 leading-relaxed mb-4">
            We use collected information solely for legitimate service purposes, including:
          </p>
          <ul className="space-y-3 text-slate-400 mb-4">
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span>Operating the security scanner and generating requested scan results.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span>Providing authenticated account features, such as displaying your personal scan history and saved reports.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span>Enforcing rate limits, quotas, and maintaining account security.</span>
            </li>
            <li className="flex items-start gap-3">
              <div className="w-1.5 h-1.5 rounded-full bg-slate-600 mt-2.5 shrink-0" />
              <span>Operating and improving the reliability of the service.</span>
            </li>
          </ul>
          <p className="text-slate-400 leading-relaxed">
            We do not use scan results to train AI models, and we do not sell personal information or scan data for advertising or marketing purposes.
          </p>
        </section>

        {/* Section 5 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">5. Access to Scan Records</h2>
          <p className="text-slate-400 leading-relaxed">
            Scan records are strictly associated with the authenticated user's account. Application access is owner-scoped, meaning users cannot browse another user's scan history. Global individual-scan browsing for administrators has been intentionally removed from the platform. Administrative dashboards rely on aggregate operational statistics.
          </p>
        </section>

        {/* Section 6 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">6. Data Security</h2>
          <p className="text-slate-400 leading-relaxed">
            URLScanOnline uses modern access controls and standard security practices appropriate to the application to protect your data. While we strive to protect your information, no system can guarantee absolute security, zero data breaches, or perfect confidentiality. We encourage users to practice good credential hygiene.
          </p>
        </section>

        {/* Section 7 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">7. Retention & Deletion</h2>
          <p className="text-slate-400 leading-relaxed">
            Authenticated scan records are maintained to provide persistent Scan History and Saved Reports. Retention depends on the account feature and current service functionality; there is currently no fixed automated deletion period. Users who wish to have their account or associated scan records deleted can submit a request to contact@urlscanonline.com.
          </p>
        </section>

        {/* Section 8 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">8. Third-Party Service Providers</h2>
          <p className="text-slate-400 leading-relaxed">
            URLScanOnline relies on service providers needed to operate functions such as hosting, authentication, and email delivery. Those providers may process information on our behalf as necessary to provide their services. Information is not made available to other URLScanOnline users through these services.
          </p>
        </section>

        {/* Section 9 */}
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-6 md:p-8">
          <h2 className="text-2xl font-bold text-slate-50 mb-4">9. Your Responsibilities</h2>
          <p className="text-slate-400 leading-relaxed">
            As outlined in our <Link to="/terms" className="text-indigo-400 hover:text-indigo-300">Terms of Service</Link>, you are responsible for ensuring that you only scan systems you own or are authorized to assess. Avoid submitting highly sensitive URLs unnecessarily, and ensure you protect your account credentials.
          </p>
        </section>

        {/* Section 10 CTA */}
        <section className="rounded-2xl border border-indigo-500/30 bg-gradient-to-r from-indigo-950/40 via-slate-900/80 to-slate-900/40 p-8 sm:p-12 text-center">
          <h3 className="text-2xl sm:text-3xl font-bold text-slate-50 tracking-tight mb-4">
            Questions About Your Privacy?
          </h3>
          <p className="text-sm text-slate-400 leading-relaxed mb-6">
            If you have questions about this Privacy Policy or how your data is handled, please contact us at: <br/>
            <strong className="text-slate-300 mt-2 inline-block">contact@urlscanonline.com</strong>
          </p>
          <div className="flex flex-wrap items-center justify-center gap-4">
            <Link
              to="/contact"
              className="rounded-xl bg-indigo-600 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-indigo-600/30 hover:bg-indigo-500 transition-all"
            >
              Contact Us
            </Link>
          </div>
        </section>

      </div>
    </div>
  );
};

export default PrivacyPolicy;
