import React from 'react';
import { Shield } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useSEO } from '../hooks/useSEO';

const PrivacyPolicy = () => {
  useSEO({
    title: 'Privacy Policy | URLScanOnline',
    description: 'Learn how URLScanOnline handles account information, scan data, scan history, access controls, data retention, and privacy.',
    path: '/privacy-policy'
  });

  return (
    <div className="flex-1 w-full max-w-4xl mx-auto p-4 sm:p-6 lg:p-8 overflow-y-auto space-y-12 pb-24">
      <header className="space-y-4">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-500/10 text-blue-400 text-sm font-semibold mb-2">
          <Shield className="w-4 h-4" />
          Privacy
        </div>
        <h1 className="text-4xl md:text-5xl font-black text-slate-50 tracking-tight">
          Privacy Policy
        </h1>
        <p className="text-lg text-slate-400 max-w-2xl">
          Learn how URLScanOnline collects, uses, stores, and protects information associated with your use of the service.
        </p>
        <div className="text-sm text-slate-500 pt-4">
          Last updated: September 2026
        </div>
      </header>

      <div className="prose prose-invert prose-slate max-w-none prose-headings:text-slate-50 prose-a:text-indigo-400 hover:prose-a:text-indigo-300">
        
        <h2>1. Information We Collect</h2>
        <p>
          We only collect information necessary to operate URLScanOnline and provide its core security scanning functionality:
        </p>
        <ul>
          <li><strong>Account Information:</strong> If you create an account, we collect basic account information such as your email address.</li>
          <li><strong>Scan Target Information:</strong> The domain names or URLs you submit to the scanner for analysis.</li>
          <li><strong>Scan Results:</strong> Security findings and report data generated by our automated checks.</li>
          <li><strong>Technical/Service Information:</strong> Technical information, such as an IP address, may be processed where needed for rate limiting, security, and abuse prevention.</li>
          <li><strong>Contact Information:</strong> Information you voluntarily submit when contacting our support or security teams.</li>
        </ul>

        <h2>2. Scan Data & Scan History</h2>
        <p>
          URLScanOnline does not maintain scan history for general administrative browsing or make one user's scan records available to another user.
        </p>
        <p>
          For authenticated users, scan records may be stored to provide account features such as Scan History and Saved Reports. These records are associated with the user's account so that the user can return to previous results.
        </p>
        <p>
          Normal application access is owner-scoped. A signed-in user can access only scan records associated with their own account.
        </p>
        <p>
          URLScanOnline administrators do not have a general Admin Control interface for browsing individual users' scan histories. Aggregate, non-identifying statistics (such as total platform scan counts) may be used for platform administration without exposing individual scan records.
        </p>

        <h2>3. Guest Scans</h2>
        <p>
          Guest scans are processed to generate the requested report and are not persisted to an account scan-history database. Technical information such as an IP address may be processed for rate limiting and abuse prevention.
        </p>

        <h2>4. How We Use Information</h2>
        <p>
          We use collected information solely for legitimate service purposes, including:
        </p>
        <ul>
          <li>Operating the security scanner and generating requested scan results.</li>
          <li>Providing authenticated account features, such as displaying your personal scan history and saved reports.</li>
          <li>Enforcing rate limits, quotas, and maintaining account security.</li>
          <li>Operating and improving the reliability of the service.</li>
        </ul>
        <p>
          We do not use scan results to train AI models, and we do not sell personal information or scan data for advertising or marketing purposes.
        </p>

        <h2>5. Access to Scan Records</h2>
        <p>
          Scan records are strictly associated with the authenticated user's account. Application access is owner-scoped, meaning users cannot browse another user's scan history. Global individual-scan browsing for administrators has been intentionally removed from the platform. Administrative dashboards rely on aggregate operational statistics.
        </p>

        <h2>6. Data Security</h2>
        <p>
          URLScanOnline uses modern access controls and standard security practices appropriate to the application to protect your data. While we strive to protect your information, no system can guarantee absolute security, zero data breaches, or perfect confidentiality. We encourage users to practice good credential hygiene.
        </p>

        <h2>7. Retention & Deletion</h2>
        <p>
          Authenticated scan records are maintained to provide persistent Scan History and Saved Reports. Retention depends on the account feature and current service functionality; there is currently no fixed automated deletion period. Users who wish to have their account or associated scan records deleted can submit a request to contact@urlscanonline.com.
        </p>

        <h2>8. Third-Party Service Providers</h2>
        <p>
          URLScanOnline relies on service providers needed to operate functions such as hosting, authentication, and email delivery. Those providers may process information on our behalf as necessary to provide their services. Information is not made available to other URLScanOnline users through these services.
        </p>

        <h2>9. Your Responsibilities</h2>
        <p>
          As outlined in our <Link to="/terms">Terms of Service</Link>, you are responsible for ensuring that you only scan systems you own or are authorized to assess. Avoid submitting highly sensitive URLs unnecessarily, and ensure you protect your account credentials.
        </p>

        <h2>10. Questions About Your Privacy?</h2>
        <p>
          If you have questions about this Privacy Policy or how your data is handled, please contact us at: <strong>contact@urlscanonline.com</strong>.
        </p>
        
        <div className="mt-8 pt-8 border-t border-slate-800">
          <Link 
            to="/contact"
            className="inline-flex items-center gap-2 bg-indigo-600 hover:bg-indigo-500 text-white px-6 py-3 rounded-xl font-medium transition-colors"
          >
            Contact Us
          </Link>
        </div>

      </div>
    </div>
  );
};

export default PrivacyPolicy;